apiVersion: v1
kind: Service
metadata:
  name: chatting-backend-svc
  labels:
    app: chatting-backend-svc
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      name: chatting
      protocol: TCP
      targetPort: 8080
  selector:
    app: chatting
